export const ADD_BILL = 'ADD_BILL';

export const OPEN_ADD_BILL_MODAL = 'OPEN_ADD_BILL_MODAL';

export const CLOSE_ADD_BILL_MODAL = 'CLOSE_ADD_BILL_MODAL';

export const SET_SELECTED_BILLS = 'SET_SELECTED_BILLS';

export const SET_PROVIDERS = 'SET_PROVIDERS';

export const SET_BILL_TYPES = 'SET_BILL_TYPES';

export const SET_BILLS = 'SET_BILLS';

export const RESET_BILL_TABLE = 'RESET_BILL_TABLE';

export const SET_SELECTED_BILL_TYPE = 'SET_SELECTED_BILL_TYPE';